name: default-code
services:
  code:
    container_name: code
    deploy:
      resources:
        reservations:
          cpus: "0.2"
          memory: 512m
    domainname: example.com
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      PROXY_DOMAIN: code.example.com
      PASSWORD: yourpassword
      PWA_APPNAME: code-server
    hostname: code
    image: lscr.io/linuxserver/code-server:latest
    ports:
      - name: http
        published: 8443
        target: 8443
        protocol: TCP
    pull_policy: if_not_present
    restart: always
    volumes:
      - type: volume
        source: config
        target: /config
      - type: volume
        source: data
        target: /data
      - read_only: true
        type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  config:
    name: code-config
    driver: local
  data:
    name: code-data
    driver: local
    driver_opts:
      o: size=3g
      type: tmpfs
      device: tmpfs
